// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDckXUM3PtU7IXbWPHQUia80cBBL_4cih0',
    appId: '1:105781192694:web:6c720522700ba725b949d7',
    messagingSenderId: '105781192694',
    projectId: 'purisanjuan-643f5',
    authDomain: 'purisanjuan-643f5.firebaseapp.com',
    storageBucket: 'purisanjuan-643f5.firebasestorage.app',
    measurementId: 'G-Y1ZWBGJ700',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPvlKkgw2X4xSz6QZeWn5eG7N03JtN_Fc',
    appId: '1:105781192694:android:7e049a88c3793842b949d7',
    messagingSenderId: '105781192694',
    projectId: 'purisanjuan-643f5',
    storageBucket: 'purisanjuan-643f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVLWQW3SPFy6Lb0S82hXA5VKhkb_X89hg',
    appId: '1:105781192694:ios:d076721d35bee4d2b949d7',
    messagingSenderId: '105781192694',
    projectId: 'purisanjuan-643f5',
    storageBucket: 'purisanjuan-643f5.firebasestorage.app',
    iosBundleId: 'com.example.yanoimport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVLWQW3SPFy6Lb0S82hXA5VKhkb_X89hg',
    appId: '1:105781192694:ios:d076721d35bee4d2b949d7',
    messagingSenderId: '105781192694',
    projectId: 'purisanjuan-643f5',
    storageBucket: 'purisanjuan-643f5.firebasestorage.app',
    iosBundleId: 'com.example.yanoimport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDckXUM3PtU7IXbWPHQUia80cBBL_4cih0',
    appId: '1:105781192694:web:b054157cabb88a47b949d7',
    messagingSenderId: '105781192694',
    projectId: 'purisanjuan-643f5',
    authDomain: 'purisanjuan-643f5.firebaseapp.com',
    storageBucket: 'purisanjuan-643f5.firebasestorage.app',
    measurementId: 'G-81LXP9JNLG',
  );
}
